"""Embed the compiled DALI bootloader into this firmware at build time.

Reads the bootloader binary from the sibling Bootloader/ project and emits
src/bl_image.h as a C byte array, so the emergency flasher always carries
the current bootloader without any manual copy step.

Runs as a PlatformIO pre-build script (see platformio.ini).
"""
import os

Import("env")  # noqa: F821  (injected by PlatformIO)

PROJECT_DIR = env["PROJECT_DIR"]  # noqa: F821
BL_DIR = os.path.normpath(os.path.join(PROJECT_DIR, "..", "Bootloader"))

# Same two candidates flash.bat accepts: PlatformIO build, then build.bat legacy
CANDIDATES = [
    os.path.join(BL_DIR, ".pio", "build", "dali_bootloader", "firmware.bin"),
    os.path.join(BL_DIR, "dali_bootloader.bin"),
]

BOOT_AREA_SIZE = 1920
OUT_HEADER = os.path.join(PROJECT_DIR, "src", "bl_image.h")


def main():
    src = next((p for p in CANDIDATES if os.path.isfile(p)), None)
    if src is None:
        raise SystemExit(
            "ERROR: no bootloader binary found. Build it first:\n"
            "  cd ../Bootloader && pio run\n"
            "Looked for:\n  " + "\n  ".join(CANDIDATES)
        )

    with open(src, "rb") as f:
        blob = f.read()

    if len(blob) > BOOT_AREA_SIZE:
        raise SystemExit(
            "ERROR: bootloader is %d bytes, boot area holds %d."
            % (len(blob), BOOT_AREA_SIZE)
        )

    # Fletcher-16 over the image — the flasher verifies the blob against
    # this before it touches the boot area, so a corrupted build cannot
    # brick the device.
    fa = fb = 0
    for byte in blob:
        fa = (fa + byte) & 0xFF
        fb = (fb + fa) & 0xFF

    lines = [
        "/* AUTO-GENERATED by embed_bootloader.py — DO NOT EDIT.",
        " * Source: %s" % os.path.relpath(src, PROJECT_DIR).replace("\\", "/"),
        " */",
        "#ifndef BL_IMAGE_H",
        "#define BL_IMAGE_H",
        "",
        "#include <stdint.h>",
        "",
        "#define BL_IMAGE_SIZE        %du" % len(blob),
        "#define BL_IMAGE_FLETCHER_FA 0x%02Xu" % fa,
        "#define BL_IMAGE_FLETCHER_FB 0x%02Xu" % fb,
        "",
        "static const uint8_t bl_image[BL_IMAGE_SIZE] = {",
    ]
    for i in range(0, len(blob), 12):
        chunk = blob[i:i + 12]
        lines.append("    " + " ".join("0x%02X," % b for b in chunk))
    lines += ["};", "", "#endif /* BL_IMAGE_H */", ""]

    text = "\n".join(lines)

    # Only rewrite when the content actually changed, so PlatformIO does not
    # rebuild the world on every invocation.
    old = None
    if os.path.isfile(OUT_HEADER):
        with open(OUT_HEADER, "r", encoding="utf-8") as f:
            old = f.read()
    if old != text:
        with open(OUT_HEADER, "w", encoding="utf-8") as f:
            f.write(text)

    print("Embedded bootloader: %d bytes, Fletcher-16 fa=0x%02X fb=0x%02X"
          % (len(blob), fa, fb))


main()
