Version 4
SymbolType BLOCK
RECTANGLE Normal 144 64 -32 -64
TEXT 16 0 Left 2 DC/DC
WINDOW 39 4 78 Center 0
SYMATTR Prefix X
SYMATTR SpiceModel IDEAL_DCDC
SYMATTR Value IDEAL_DCDC
SYMATTR SpiceLine Vout=5 Eff=1
SYMATTR ModelFile IDEAL_DCDC.lib
PIN -32 -48 LEFT 8
PINATTR PinName IN+
PINATTR SpiceOrder 1
PIN -32 48 LEFT 8
PINATTR PinName IN-
PINATTR SpiceOrder 2
PIN 144 -48 RIGHT 8
PINATTR PinName OUT+
PINATTR SpiceOrder 3
PIN 144 48 RIGHT 8
PINATTR PinName OUT-
PINATTR SpiceOrder 4
